"""Declare which app this process belongs to.

Mirrors ``nanny::set_app`` in the Rust SDK.

You normally never call this. ``nanny run`` reads the committed
``.nanny/app.json`` and declares the app for you, on both the plain run and
the ``--join`` path, so an app is attributed without doing anything. This
exists for the case the CLI cannot cover: a process that joins a governor and
wants to report under its own identity rather than inheriting the governor's,
or one embedded somewhere ``nanny run`` did not launch.

Identity travels in the event stream rather than being derived from the API
key, which is what lets one governor holding one credential serve many apps
and still attribute each separately — the same reason OpenTelemetry makes
``service.name`` a resource attribute instead of a transport concern.
"""

from __future__ import annotations

from typing import Any

from nanny_sdk import _client as _bridge


def set_app(app_id: str, name: str = "") -> None:
    """Declare this process's app identity to the bridge.

    Records an ``AppIdentified`` attribution event so the cloud can group runs
    by app. Deduped bridge-side, so calling it repeatedly is harmless and
    re-declaring on every request is safe.

    ``app_id`` is the permanent identity generated by ``nanny init``; ``name``
    is a display label and may change without the app becoming a different
    app. An empty ``app_id`` is ignored — identity is generated and never
    blank, so a blank one means a mistake. An empty ``name`` is allowed: the
    id identifies, the name is only how it reads.

    Passthrough mode (no bridge active) is a no-op, the same contract as
    ``instrument`` and the decorators. Fire and forget: the response is ignored
    and transport errors are swallowed, so declaring identity can never
    interrupt the agent.
    """
    if _bridge.is_passthrough() or not app_id.strip():
        return
    body: dict[str, Any] = {"app_id": app_id, "name": name}
    try:
        with _bridge._make_client(timeout=5.0) as http:
            http.post("/app", json=body, headers=_bridge._headers())
    except Exception:  # noqa: BLE001
        pass
