// nanny.toml schema, parsing, and strict validation.
//
// This crate owns one job: turn a static file into a trusted, validated config.
// If the file is missing, malformed, or contains illegal values — we fail immediately.
// No silent defaults. No guessing. No recovery.

use serde::{Deserialize, Serialize};
use std::path::Path;
use thiserror::Error;

// ── Error type ────────────────────────────────────────────────────────────────

/// Every way config loading can fail. All failures are final — there is no fallback.
#[derive(Debug, Error)]
pub enum ConfigError {
    #[error("config file not found at '{path}' — run `nanny init` to create one")]
    NotFound { path: String },

    #[error("could not read config file: {0}")]
    Io(#[from] std::io::Error),

    #[error("invalid config: {0}")]
    Parse(String),
}

// ── Top-level config ──────────────────────────────────────────────────────────

/// The full contents of a nanny.toml file.
/// Every field must be explicitly present — partial configs are rejected.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct NannyConfig {
    /// Execution mode. Determines whether the runtime operates locally or reports to an orchestrator.
    #[serde(default)]
    pub mode: Mode,

    /// Hard limits that govern every execution under this config.
    pub limits: LimitsConfig,

    /// Tool permission policy.
    #[serde(default)]
    pub tools: ToolsConfig,
}

// ── Mode ──────────────────────────────────────────────────────────────────────

/// Whether the runtime operates standalone or reports facts to a hosted orchestrator.
#[derive(Debug, Clone, Serialize, Deserialize, Default, PartialEq)]
#[serde(rename_all = "lowercase")]
pub enum Mode {
    /// Local-only. No network calls. No external dependencies. Default.
    #[default]
    Local,

    /// Managed mode. Runtime still enforces locally but sends facts to the orchestrator.
    Managed,
}

// ── Limits ────────────────────────────────────────────────────────────────────

/// Hard execution limits. All three fields are required — there are no optional limits.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct LimitsConfig {
    /// Maximum number of steps the agent may execute.
    pub max_steps: u32,

    /// Maximum cost units the agent may spend. Abstract in local mode.
    pub max_cost_units: u64,

    /// Wall-clock timeout in milliseconds. Checked at the entry of every step.
    pub timeout_ms: u64,
}

// ── Tools ─────────────────────────────────────────────────────────────────────

/// Tool permission policy. Any tool not in the allowlist causes an immediate stop.
#[derive(Debug, Clone, Serialize, Deserialize, Default)]
pub struct ToolsConfig {
    /// Explicit list of permitted tool names.
    #[serde(default)]
    pub allowed: Vec<String>,
}

// ── Load ──────────────────────────────────────────────────────────────────────

/// Load and parse a nanny.toml from disk.
///
/// Fails immediately if:
/// - The file does not exist
/// - The file cannot be read
/// - The TOML is malformed
/// - Required fields are missing
///
/// There is no fallback. No defaults are applied for missing required fields.
pub fn load(path: &Path) -> Result<NannyConfig, ConfigError> {
    if !path.exists() {
        return Err(ConfigError::NotFound {
            path: path.display().to_string(),
        });
    }

    let contents = std::fs::read_to_string(path)?;

    toml::from_str(&contents).map_err(|e| ConfigError::Parse(e.to_string()))
}

// ── Default TOML template ─────────────────────────────────────────────────────

/// The canonical starter nanny.toml written by `nanny init`.
///
/// This is a static string — not generated from structs — so the comments
/// and formatting are preserved exactly as the user will see them.
pub fn default_toml() -> &'static str {
    r#"# nanny.toml — Execution boundary configuration
# Generated by `nanny init`. Edit to match your agent's requirements.
# Documentation: https://github.com/nanny/nanny

# Execution mode: "local" (default) or "managed" (requires orchestrator config).
# In local mode, all enforcement happens on this machine with no network calls.
mode = "local"

[limits]
# Maximum number of steps the agent may execute before being stopped.
max_steps = 100

# Maximum cost units the agent may spend. In local mode these are abstract units.
# In managed mode they map to real currency via your orchestrator configuration.
max_cost_units = 1000

# Wall-clock timeout in milliseconds. 30000 = 30 seconds.
timeout_ms = 30000

[tools]
# Tools the agent is permitted to call.
# Any tool not listed here causes an immediate hard stop.
allowed = ["http_get"]
"#
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_toml_is_valid() {
        // The template we hand to users must always parse cleanly.
        let config: NannyConfig =
            toml::from_str(default_toml()).expect("default_toml() must always be valid TOML");

        assert_eq!(config.limits.max_steps, 100);
        assert_eq!(config.limits.max_cost_units, 1000);
        assert_eq!(config.limits.timeout_ms, 30000);
        assert_eq!(config.mode, Mode::Local);
        assert_eq!(config.tools.allowed, vec!["http_get"]);
    }

    #[test]
    fn missing_limits_is_rejected() {
        let bad = r#"mode = "local""#;
        assert!(
            toml::from_str::<NannyConfig>(bad).is_err(),
            "config without [limits] must be rejected"
        );
    }

    #[test]
    fn unknown_mode_is_rejected() {
        let bad = r#"
mode = "cloud"
[limits]
max_steps = 10
max_cost_units = 100
timeout_ms = 5000
"#;
        assert!(
            toml::from_str::<NannyConfig>(bad).is_err(),
            "unknown mode must be rejected"
        );
    }
}
