//! nanny — Rust SDK and CLI.
//!
//! # Usage
//!
//! ```toml
//! [dependencies]
//! nanny = "0.1"
//! ```
//!
//! ```rust,ignore
//! use nanny::{tool, rule, agent, PolicyContext};
//!
//! #[tool(cost = 10)]
//! fn search_web(query: &str) -> String { ... }
//!
//! #[rule("no_spiral")]
//! fn check_spiral(ctx: &PolicyContext) -> bool { ... }
//!
//! #[agent("researcher")]
//! fn run_research(topic: &str) { ... }
//! ```

// ── User-facing re-exports ────────────────────────────────────────────────────

/// The type passed to `#[nanny::rule]` functions.
pub use nanny_core::policy::PolicyContext;

/// All possible reasons nanny stopped execution.
pub use nanny_core::agent::state::StopReason;

/// Declare a function as a governed nanny tool.
/// See [`tool`](nanny_macros::tool) for full documentation.
pub use nanny_macros::tool;

/// Register a function as a named enforcement rule.
/// See [`rule`](nanny_macros::rule) for full documentation.
pub use nanny_macros::rule;

/// Activate a named limits set for the duration of a function.
/// See [`agent`](nanny_macros::agent) for full documentation.
pub use nanny_macros::agent;

// ── Built-in bridge tools ─────────────────────────────────────────────────────

/// Fetch a URL via nanny's built-in `http_get` bridge tool.
///
/// The request is executed by the nanny bridge — the calling process never
/// opens a network connection directly. Nanny enforces the allowlist, charges
/// cost (10 units on success), and applies the step limit before making the
/// request.
///
/// # Passthrough mode
///
/// When running outside `nanny run` (no bridge active), returns
/// `Err("bridge unavailable")`. This keeps behaviour predictable: the tool
/// always goes through nanny when a bridge is present.
///
/// # Example
///
/// ```rust,ignore
/// use nanny::PolicyContext;
/// use rig::tool::Tool;
///
/// impl Tool for MyFetchTool {
///     async fn call(&self, args: Self::Args) -> Result<Self::Output, Self::Error> {
///         tokio::task::spawn_blocking(move || {
///             nanny::http_get(args.url).map_err(MyError)
///         })
///         .await
///         .map_err(|e| MyError(e.to_string()))?
///     }
/// }
/// ```
pub fn http_get(url: String) -> Result<String, String> {
    // Evaluate local rules first — same as #[nanny::tool] does.
    // This ensures #[nanny::rule] functions (e.g. "no_loop") fire for
    // built-in bridge tools, not just developer-defined #[nanny::tool] functions.
    let mut args = std::collections::HashMap::new();
    args.insert("url".to_string(), url.clone());
    if let Some(rule_name) = runtime::evaluate_local_rules("http_get", args) {
        runtime::report_stop("RuleDenied");
        eprintln!("nanny: stopped — RuleDenied: {rule_name}");
        std::process::exit(1);
    }

    let args_json = serde_json::json!({"url": url}).to_string();
    runtime::call_bridge_tool("http_get", &args_json)
}

// ── Private runtime — for generated code only ─────────────────────────────────
//
// Everything below this line is used exclusively by code generated by
// nanny-macros. It is not a public API. Names and signatures may change
// in any release without notice.

#[doc(hidden)]
pub mod __private {
    // Re-export inventory so generated code can call
    // `::nanny::__private::inventory::submit! { ... }` without requiring
    // users to add inventory as a direct dependency.
    pub use ::inventory;

    pub use super::runtime::{
        agent_enter, agent_exit, call_bridge_tool, call_tool, evaluate_local_rules, is_active,
        report_stop, report_stop_rule, Rule, ToolVerdict,
    };
}

mod runtime {
    use nanny_core::policy::PolicyContext;
    use std::collections::HashMap;
    use std::sync::{Mutex, OnceLock};
    use std::time::Instant;

    // ── Rule registry ─────────────────────────────────────────────────────────

    /// A user-defined enforcement rule, registered via `#[nanny::rule("name")]`.
    pub struct Rule {
        pub name: &'static str,
        pub func: fn(&PolicyContext) -> bool,
    }

    inventory::collect!(Rule);

    // ── Client-side state ──────────────────────────────────────────────────────

    struct ClientState {
        start: Instant,
    }

    impl ClientState {
        fn new() -> Self {
            Self { start: Instant::now() }
        }
    }

    fn client_state() -> &'static Mutex<ClientState> {
        static STATE: OnceLock<Mutex<ClientState>> = OnceLock::new();
        STATE.get_or_init(|| Mutex::new(ClientState::new()))
    }

    // ── Bridge detection ──────────────────────────────────────────────────────

    /// Returns `true` if any bridge transport is active.
    ///
    /// Priority (checked in order):
    ///   1. `NANNY_BRIDGE_SOCKET`  — Unix domain socket (macOS/Linux local)
    ///   2. `NANNY_BRIDGE_PORT`    — TCP loopback (Windows local)
    ///   3. `NANNY_BRIDGE_ADDR`    — TCP + mTLS (network / cross-machine)
    ///   None of the above         → passthrough (no-op)
    pub fn is_active() -> bool {
        bridge_socket_path().is_some() || bridge_tcp_port().is_some() || bridge_addr().is_some()
    }

    #[cfg(unix)]
    fn bridge_socket_path() -> Option<std::path::PathBuf> {
        std::env::var("NANNY_BRIDGE_SOCKET").ok().map(std::path::PathBuf::from)
    }

    #[cfg(not(unix))]
    fn bridge_socket_path() -> Option<std::path::PathBuf> {
        None
    }

    fn bridge_tcp_port() -> Option<u16> {
        std::env::var("NANNY_BRIDGE_PORT").ok()?.parse().ok()
    }

    /// `NANNY_BRIDGE_ADDR` — host:port of the network governance server.
    /// Set automatically by `nanny run` when a server is running.
    fn bridge_addr() -> Option<String> {
        std::env::var("NANNY_BRIDGE_ADDR").ok().filter(|s| !s.is_empty())
    }

    fn session_token() -> String {
        std::env::var("NANNY_SESSION_TOKEN").unwrap_or_default()
    }

    // ── mTLS cert resolution ───────────────────────────────────────────────────
    //
    // When NANNY_BRIDGE_ADDR is set, the SDK uses these certs to authenticate
    // with the server. `nanny run` auto-injects them from ~/.nanny/certs/ on the
    // local machine. Cross-machine deployments set the env vars manually.
    //
    // Two formats are accepted for all three NANNY_BRIDGE_CERT/KEY/CA env vars:
    //
    //   File path:   NANNY_BRIDGE_CA=/path/to/ca.crt
    //   Inline PEM:  NANNY_BRIDGE_CA="-----BEGIN CERTIFICATE-----\n..."
    //
    // Inline PEM works without a filesystem — useful in Docker/k8s where secrets
    // are injected as env var values rather than mounted files.
    //
    // NANNY_BRIDGE_CERT may be a combined cert+key PEM bundle, in which case
    // NANNY_BRIDGE_KEY can be omitted.

    fn default_nanny_certs_dir() -> std::path::PathBuf {
        dirs::home_dir()
            .expect("cannot determine home directory")
            .join(".nanny")
            .join("certs")
    }

    /// Resolve PEM bytes from an env var.
    ///
    /// - Env var starts with `-----BEGIN` → treat as inline PEM, return the bytes.
    /// - Env var is a non-empty string (not PEM) → treat as file path, read the file.
    /// - Env var is absent → try the fallback path; return `None` if it doesn't exist.
    fn resolve_pem(env_var: &str, fallback: std::path::PathBuf) -> Option<Vec<u8>> {
        match std::env::var(env_var) {
            Ok(val) if val.starts_with("-----BEGIN") => Some(val.into_bytes()),
            Ok(val) if !val.is_empty()               => std::fs::read(&val).ok(),
            _                                        => std::fs::read(&fallback).ok(),
        }
    }

    // ── HTTP transport ────────────────────────────────────────────────────────

    struct BridgeResponse {
        status: u16,
        body:   String,
    }

    fn http_get(path: &str) -> Option<BridgeResponse> {
        let token = session_token();
        let req = format!(
            "GET {path} HTTP/1.1\r\n\
             Host: localhost\r\n\
             X-Nanny-Session-Token: {token}\r\n\
             Connection: close\r\n\
             \r\n"
        );

        #[cfg(unix)]
        if let Some(sock) = bridge_socket_path() {
            use std::io::{Read, Write};
            use std::os::unix::net::UnixStream;
            let mut stream = UnixStream::connect(&sock).ok()?;
            stream.write_all(req.as_bytes()).ok()?;
            let mut raw = String::new();
            stream.read_to_string(&mut raw).ok()?;
            return parse_http_response(&raw);
        }

        if let Some(port) = bridge_tcp_port() {
            use std::io::{Read, Write};
            use std::net::TcpStream;
            let mut stream = TcpStream::connect(("127.0.0.1", port)).ok()?;
            stream.write_all(req.as_bytes()).ok()?;
            let mut raw = String::new();
            stream.read_to_string(&mut raw).ok()?;
            return parse_http_response(&raw);
        }

        // Transport 3: NANNY_BRIDGE_ADDR — mTLS over TCP.
        if let Some(addr) = bridge_addr() {
            return http_get_tls(&addr, path);
        }

        None
    }

    fn http_post(path: &str, body: &str) -> Option<BridgeResponse> {
        let token = session_token();
        let req = format!(
            "POST {path} HTTP/1.1\r\n\
             Host: localhost\r\n\
             X-Nanny-Session-Token: {token}\r\n\
             Content-Type: application/json\r\n\
             Content-Length: {len}\r\n\
             Connection: close\r\n\
             \r\n\
             {body}",
            len = body.len()
        );

        #[cfg(unix)]
        if let Some(sock) = bridge_socket_path() {
            use std::io::{Read, Write};
            use std::os::unix::net::UnixStream;
            let mut stream = UnixStream::connect(&sock).ok()?;
            stream.write_all(req.as_bytes()).ok()?;
            let mut raw = String::new();
            stream.read_to_string(&mut raw).ok()?;
            return parse_http_response(&raw);
        }

        if let Some(port) = bridge_tcp_port() {
            use std::io::{Read, Write};
            use std::net::TcpStream;
            let mut stream = TcpStream::connect(("127.0.0.1", port)).ok()?;
            stream.write_all(req.as_bytes()).ok()?;
            let mut raw = String::new();
            stream.read_to_string(&mut raw).ok()?;
            return parse_http_response(&raw);
        }

        // Transport 3: NANNY_BRIDGE_ADDR — mTLS over TCP.
        if let Some(addr) = bridge_addr() {
            return http_post_tls(&addr, path, body);
        }

        None
    }

    // ── mTLS transport (NANNY_BRIDGE_ADDR) ────────────────────────────────────

    /// Build a reqwest blocking client with mTLS client cert.
    ///
    /// Loads cert/key/CA from env vars or ~/.nanny/certs/ defaults.
    /// Returns `None` if cert files are missing or malformed — callers treat
    /// this as bridge unavailable (fail-closed when is_active() is true).
    fn build_tls_client() -> Option<reqwest::blocking::Client> {
        let certs_dir = default_nanny_certs_dir();

        // NANNY_BRIDGE_CERT may be a combined cert+key PEM bundle, in which case
        // NANNY_BRIDGE_KEY can be omitted (empty bytes are harmless when appended).
        let cert_pem = resolve_pem("NANNY_BRIDGE_CERT", certs_dir.join("client.crt"))?;
        let key_pem  = resolve_pem("NANNY_BRIDGE_KEY",  certs_dir.join("client.key"))
            .unwrap_or_default();
        let ca_pem   = resolve_pem("NANNY_BRIDGE_CA",   certs_dir.join("ca.crt"))?;

        // reqwest::Identity requires PEM cert + key concatenated.
        let mut identity_pem = cert_pem;
        identity_pem.extend_from_slice(&key_pem);
        let identity = reqwest::Identity::from_pem(&identity_pem).ok()?;
        let ca_cert  = reqwest::Certificate::from_pem(&ca_pem).ok()?;

        reqwest::blocking::Client::builder()
            .add_root_certificate(ca_cert)
            .identity(identity)
            .use_rustls_tls()   // force rustls — Identity::from_pem produces a rustls identity
            .build()
            .ok()
    }

    fn http_get_tls(addr: &str, path: &str) -> Option<BridgeResponse> {
        let client = build_tls_client()?;
        let url = format!("https://{addr}{path}");
        let resp = client
            .get(&url)
            .header("X-Nanny-Session-Token", session_token())
            .send()
            .ok()?;
        let status = resp.status().as_u16();
        let body = resp.text().ok()?;
        Some(BridgeResponse { status, body })
    }

    fn http_post_tls(addr: &str, path: &str, body: &str) -> Option<BridgeResponse> {
        let client = build_tls_client()?;
        let url = format!("https://{addr}{path}");
        let resp = client
            .post(&url)
            .header("X-Nanny-Session-Token", session_token())
            .header("Content-Type", "application/json")
            .body(body.to_string())
            .send()
            .ok()?;
        let status = resp.status().as_u16();
        let resp_body = resp.text().ok()?;
        Some(BridgeResponse { status, body: resp_body })
    }

    fn parse_http_response(raw: &str) -> Option<BridgeResponse> {
        let (headers, body) = raw.split_once("\r\n\r\n")?;
        let status_line = headers.lines().next()?;
        let status: u16 = status_line.split_whitespace().nth(1)?.parse().ok()?;
        Some(BridgeResponse { status, body: body.to_string() })
    }

    // ── Rule evaluation ───────────────────────────────────────────────────────

    /// Evaluate all locally-registered rules for `tool_name`.
    /// Returns the name of the first denying rule, or `None` if all pass.
    ///
    /// Fetches all live counters from the bridge `/status` endpoint before
    /// evaluating rules — `BridgeState` is the single source of truth.
    ///
    /// Fails closed if the bridge is active but unreachable: rules cannot be
    /// evaluated reliably against zeroed counters.
    /// Manifesto: "silently continuing execution is always a bug."
    pub fn evaluate_local_rules(
        tool_name: &str,
        args: HashMap<String, String>,
    ) -> Option<&'static str> {
        let elapsed_ms = client_state().lock().unwrap().start.elapsed().as_millis() as u64;

        // Fetch all tracked counters from the bridge (authoritative state).
        // If the bridge is active but unreachable, fail closed — same logic as
        // call_tool, which returns ToolVerdict::Stop("BridgeUnavailable").
        let status = match fetch_bridge_status() {
            Some(s) => s,
            None if is_active() => {
                report_stop("BridgeUnavailable");
                eprintln!("nanny: stopped — BridgeUnavailable (bridge unreachable during rule evaluation)");
                std::process::exit(1);
            }
            // Passthrough mode (no bridge env vars) — zeros are correct; rules
            // still run but counters will be empty, which is expected offline.
            None => BridgeStatus {
                step_count:        0,
                cost_units_spent:  0,
                tool_call_counts:  HashMap::new(),
                tool_call_history: Vec::new(),
            },
        };

        let ctx = PolicyContext {
            requested_tool:    Some(tool_name.to_string()),
            tool_call_counts:  status.tool_call_counts,
            tool_call_history: status.tool_call_history,
            last_tool_args:    args,
            elapsed_ms,
            step_count:        status.step_count,
            cost_units_spent:  status.cost_units_spent,
            ..PolicyContext::default()
        };

        for rule in inventory::iter::<Rule> {
            if !(rule.func)(&ctx) {
                return Some(rule.name);
            }
        }
        None
    }

    /// Counters fetched from the bridge `/status` endpoint.
    struct BridgeStatus {
        step_count:        u32,
        cost_units_spent:  u64,
        tool_call_counts:  HashMap<String, u32>,
        tool_call_history: Vec<String>,
    }

    /// Fetch all live counters from the bridge /status endpoint.
    /// Returns `None` if the bridge is unreachable or returns unexpected data.
    /// Callers must check `is_active()` to decide whether to fail closed or use
    /// zeroed defaults (passthrough mode).
    fn fetch_bridge_status() -> Option<BridgeStatus> {
        let resp = match http_get("/status") {
            Some(r) if r.status == 200 => r,
            _ => return None,
        };
        let v: serde_json::Value = match serde_json::from_str(&resp.body) {
            Ok(v) => v,
            Err(_) => return None,
        };
        // Bridge wire names: "step" → step_count, "cost_spent" → cost_units_spent
        let step_count = v.get("step")
            .and_then(|s| s.as_u64())
            .unwrap_or(0) as u32;
        let cost_units_spent = v.get("cost_spent")
            .and_then(|c| c.as_u64())
            .unwrap_or(0);
        let tool_call_counts = v.get("tool_call_counts")
            .and_then(|c| serde_json::from_value(c.clone()).ok())
            .unwrap_or_default();
        let tool_call_history = v.get("tool_call_history")
            .and_then(|h| serde_json::from_value(h.clone()).ok())
            .unwrap_or_default();
        Some(BridgeStatus { step_count, cost_units_spent, tool_call_counts, tool_call_history })
    }

    // ── Tool call ─────────────────────────────────────────────────────────────

    /// What the bridge decided about a tool call.
    #[derive(Debug)]
    pub enum ToolVerdict {
        /// Allowed — run the original function body.
        Run,
        /// Denied or stopped — panic with this message.
        Stop(String),
    }

    /// POST /tool/call to the bridge.
    pub fn call_tool(tool_name: &str, cost: u64) -> ToolVerdict {
        let body = format!(r#"{{"tool":"{tool_name}","cost":{cost}}}"#);
        match http_post("/tool/call", &body) {
            Some(resp) if resp.status == 200 && resp.body.contains("\"allowed\"") => {
                ToolVerdict::Run
            }
            Some(resp) if resp.status == 200 => {
                let reason = extract_str(&resp.body, "rule_name")
                    .map(|r| format!("RuleDenied: {r}"))
                    .or_else(|| extract_str(&resp.body, "tool_name").map(|t| format!("ToolDenied: {t}")))
                    .or_else(|| extract_str(&resp.body, "reason"))
                    .unwrap_or_else(|| "ToolDenied".to_string());
                ToolVerdict::Stop(reason)
            }
            Some(resp) if resp.status == 410 => {
                let reason = extract_str(&resp.body, "reason")
                    .unwrap_or_else(|| "ExecutionStopped".to_string());
                ToolVerdict::Stop(reason)
            }
            _ => {
                // If the bridge is unreachable while we are in a governed run,
                // the enforcement guarantee is broken — fail closed rather than
                // silently allowing the tool call to proceed ungoverned.
                // If we are not in a governed run (passthrough mode, no env vars
                // set), is_active() returns false and we run normally.
                if is_active() {
                    ToolVerdict::Stop("BridgeUnavailable".to_string())
                } else {
                    ToolVerdict::Run
                }
            }
        }
    }

    /// POST /tool/call for a bridge-side tool (e.g. `http_get`).
    ///
    /// Unlike `call_tool` (which is for user-defined tools), this forwards
    /// `args_json` to the bridge and returns the tool's actual output content
    /// on success. The bridge executes the tool itself — the child process
    /// never runs any local logic for it.
    ///
    /// Returns `Err(reason)` if the call is denied, stopped, or the bridge
    /// is unavailable.
    pub fn call_bridge_tool(tool_name: &str, args_json: &str) -> Result<String, String> {
        let body = format!(r#"{{"tool":"{tool_name}","args":{args_json}}}"#);
        match http_post("/tool/call", &body) {
            Some(resp) if resp.status == 200 => {
                // Use serde_json so the result field is safely decoded even
                // when it contains HTML with escaped quotes or special chars.
                let v: serde_json::Value = serde_json::from_str(&resp.body)
                    .map_err(|e| e.to_string())?;
                if v["status"] == "allowed" {
                    Ok(v["result"].as_str().unwrap_or("").to_string())
                } else {
                    let reason = v["rule_name"].as_str()
                        .map(|r| format!("RuleDenied: {r}"))
                        .or_else(|| v["tool_name"].as_str().map(|t| format!("ToolDenied: {t}")))
                        .or_else(|| v["reason"].as_str().map(str::to_string))
                        .unwrap_or_else(|| "Denied".to_string());
                    Err(reason)
                }
            }
            Some(resp) if resp.status == 410 => {
                let reason = serde_json::from_str::<serde_json::Value>(&resp.body)
                    .ok()
                    .and_then(|v| v["reason"].as_str().map(str::to_string))
                    .unwrap_or_else(|| "ExecutionStopped".to_string());
                Err(reason)
            }
            Some(resp) if resp.status == 500 => {
                // Tool execution failed bridge-side (e.g. network error in http_get).
                let message = serde_json::from_str::<serde_json::Value>(&resp.body)
                    .ok()
                    .and_then(|v| v["message"].as_str().map(str::to_string))
                    .unwrap_or_else(|| "tool execution failed".to_string());
                Err(format!("ToolFailed: {message}"))
            }
            _ => Err("bridge unavailable".to_string()),
        }
    }

    /// POST /stop to the bridge — report a stop reason before calling exit(1).
    ///
    /// The bridge records this reason so the CLI emits it in `ExecutionStopped`
    /// instead of falling back to `ProcessCrashed`. Silently ignored if the
    /// bridge is unreachable.
    pub fn report_stop(reason: &str) {
        let body = serde_json::json!({"reason": reason}).to_string();
        let _ = http_post("/stop", &body);
    }

    /// POST /stop with RuleDenied metadata so the bridge can emit the NDJSON event.
    ///
    /// Carries `tool` and `rule_name` so `handle_stop` can append a `RuleDenied`
    /// event to the stream — client-side rule denials never reach `/tool/call`,
    /// so the bridge would otherwise have no way to emit the event.
    pub fn report_stop_rule(tool: &str, rule_name: &str) {
        let body = serde_json::json!({
            "reason":    "RuleDenied",
            "tool":      tool,
            "rule_name": rule_name,
        }).to_string();
        let _ = http_post("/stop", &body);
    }

    // ── Agent enter / exit ────────────────────────────────────────────────────

    /// POST /agent/enter — switch to a named limits set.
    pub fn agent_enter(name: &str) {
        let body = serde_json::json!({"name": name}).to_string();
        if let Some(resp) = http_post("/agent/enter", &body) {
            if resp.status == 404 {
                panic!("nanny: agent limits set '{name}' not found in nanny.toml");
            }
        }
    }

    /// POST /agent/exit — revert to global limits.
    pub fn agent_exit() {
        http_post("/agent/exit", "{}");
    }

    // ── JSON helpers ──────────────────────────────────────────────────────────

    fn extract_str(json: &str, key: &str) -> Option<String> {
        let needle = format!("\"{key}\":");
        let after = json.find(&needle).map(|i| json[i + needle.len()..].trim_start())?;
        let inner = after.strip_prefix('"')?;
        let end = inner.find('"')?;
        Some(inner[..end].to_string())
    }
}

// ── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::__private::*;

    #[test]
    fn inactive_when_no_env_vars() {
        // SAFETY: std::env::remove_var is unsound when other threads are
        // reading the environment concurrently (deprecated in Rust 1.85).
        // This test runs in a single-threaded harness with no other env
        // readers, so the mutation is safe here. Do not copy this pattern
        // into multi-threaded production code.
        unsafe {
            std::env::remove_var("NANNY_BRIDGE_SOCKET");
            std::env::remove_var("NANNY_BRIDGE_PORT");
            std::env::remove_var("NANNY_BRIDGE_ADDR");
        }
        assert!(!is_active());
    }

    // Note: we do not add a parallel test for NANNY_BRIDGE_ADDR → is_active() because
    // all env-var tests mutate shared process state. The bridge_addr() path is covered
    // by the is_passthrough() logic tested via `inactive_when_no_env_vars`.

    #[test]
    fn no_rules_registered_allows_all() {
        assert!(evaluate_local_rules("any_tool", ::std::collections::HashMap::new()).is_none());
    }
}
