"""``nanny_sdk.set_app`` — declare which app this process belongs to.

Mirrors the Rust SDK's ``nanny::set_app``. Rust leads, Python mirrors, so the
guarantees asserted here are the same ones the Rust tests pin: deduped
bridge-side, no-op in passthrough, never able to interrupt the agent.
"""

from __future__ import annotations

from typing import Any

import pytest
from pytest_httpserver import HTTPServer

from nanny_sdk import set_app


def _app_posts(bridge: HTTPServer) -> list[dict[str, Any]]:
    """JSON bodies POSTed to ``/app``, in order."""
    return [
        req.get_json() for req, _resp in bridge.log if req.path == "/app" and req.method == "POST"
    ]


def _expect_app(bridge: HTTPServer) -> None:
    bridge.expect_request("/app", method="POST").respond_with_json({"status": "ok"})


def test_declares_app_id_and_name(mock_bridge: HTTPServer) -> None:
    _expect_app(mock_bridge)
    set_app("app_70c74914f3694d03a18c70dbca8fb8d8", "gotm-nanny")
    assert _app_posts(mock_bridge) == [
        {"app_id": "app_70c74914f3694d03a18c70dbca8fb8d8", "name": "gotm-nanny"}
    ]


def test_carries_the_session_token(mock_bridge: HTTPServer) -> None:
    # Every bridge call is authenticated; a declaration is no exception.
    _expect_app(mock_bridge)
    set_app("app_abc", "whatever")
    headers = [req.headers for req, _ in mock_bridge.log if req.path == "/app"]
    assert headers and headers[0].get("X-Nanny-Session-Token") == "test-token"


def test_empty_name_is_allowed(mock_bridge: HTTPServer) -> None:
    # The id identifies; the name is only a label, so a blank one is not the
    # malformed case that a blank id is.
    _expect_app(mock_bridge)
    set_app("app_abc")
    assert _app_posts(mock_bridge) == [{"app_id": "app_abc", "name": ""}]


@pytest.mark.parametrize("app_id", ["", "   "])
def test_blank_app_id_is_ignored(mock_bridge: HTTPServer, app_id: str) -> None:
    # Identity is generated by `nanny init` and is never blank, so a blank one
    # means a mistake — don't send it and don't fail either.
    _expect_app(mock_bridge)
    set_app(app_id, "some-name")
    assert _app_posts(mock_bridge) == []


def test_noop_in_passthrough(monkeypatch: pytest.MonkeyPatch) -> None:
    # Running outside `nanny run` must not attempt a connection, exactly as the
    # decorators and `instrument` behave. No bridge fixture here on purpose.
    for var in ("NANNY_BRIDGE_SOCKET", "NANNY_BRIDGE_PORT", "NANNY_BRIDGE_ADDR"):
        monkeypatch.delenv(var, raising=False)
    set_app("app_abc", "gotm-nanny")  # must not raise or hang


def test_a_failing_bridge_never_interrupts_the_agent(mock_bridge: HTTPServer) -> None:
    # Fire and forget: attribution is never worth failing a run over.
    mock_bridge.expect_request("/app", method="POST").respond_with_data("nope", status=500)
    set_app("app_abc", "gotm-nanny")  # must not raise


def test_redeclaring_is_safe(mock_bridge: HTTPServer) -> None:
    # Dedup lives bridge-side (record_app only appends on change), so the SDK
    # may safely re-declare; what matters here is that repeated calls neither
    # raise nor mangle the body.
    _expect_app(mock_bridge)
    set_app("app_abc", "gotm-nanny")
    set_app("app_abc", "gotm-nanny")
    assert _app_posts(mock_bridge) == [
        {"app_id": "app_abc", "name": "gotm-nanny"},
        {"app_id": "app_abc", "name": "gotm-nanny"},
    ]
